### ISSUE TITLE
Website: add SGM to home dashboard

### ISSUE THREAD

**Issue by siddharth-krishna** [open-energy-transition/solver-benchmark#58]
> The shifted geometric mean SGM of the n nonnegative numbers v[1],...v[n] is
>     SGM = exp(sum{i in 1..n} ln(max(1,v[i]+sh))/n) - sh, sh nonnegative
> In our benchmarks, where the v[i] are Wallclock seconds, we use sh = 10.
> Then we scale the means by dividing them by the smallest mean.

Source: https://plato.asu.edu/ftp/shgeom.html

In the home page of the website, we can add a table which shows the SGM of runtimes of each solver on all the benchmarks that it solved successfully. If the user filters the benchmarks, this SGM value should update to be the SGM of the filtered benchmarks.

Some questions to be answered still:

- [x] Does Mittlemann also exclude the benchmarks that timed out? See https://plato.asu.edu/ftp/lpopt.html for an example.
- [x] Does it also make sense to report the SGM of memory consumption?
- [ ] Does it make sense to include all sizes of each benchmark? Or should we only take the SGM of one size of each benchmark?

**Comment by jacek-oet** [comment]
>  Does Mittlemann also exclude the benchmarks that timed out? See https://plato.asu.edu/ftp/lpopt.html for an example.

@siddharth-krishna 
In Hans Mittelmann's benchmarks, timeouts are not excluded. Instead, they are assigned a maximum runtime value of 15,000 seconds. 

**Calculation for COPT:**

- The raw shifted geometric mean (SGM) for COPT is **38.67**. 
- The scaled shifted geometric mean of runtimes is calculated by dividing the raw SGM by the smallest SGM value (1, from the table). 

```python
import numpy as np

# COPT runtimes from the table
runtimes = [
    2, 4, 55, 59, 1, 4, 3, 42, 1, 25, 1, 13, 5, 5, 1, 11, 4, 3, 4, 2, 3, 15,
    6, 1, 19, 12, 13, 32, 4, 2, 46, 5, 6, 3, 11, 11, 6, 2, 39, 20, 346, 130, 5294, 212, 9, 801, 22, 383, 75,
    74, 71, 104, 49, 303, 1141, 187, 97, 120, 130, 864, 93, 312, 1544, 617, 163
]

# Shift value
shift = 10

# Step 1: Apply the shift to each runtime
shifted_runtimes = [max(1, runtime + shift) for runtime in runtimes]

# Step 2: Compute the natural logarithm of the shifted runtimes
log_shifted_runtimes = [np.log(value) for value in shifted_runtimes]

# Step 3: Compute the arithmetic mean of the logarithms
mean_log = np.mean(log_shifted_runtimes)

# Step 4: Exponentiate and subtract the shift to calculate the raw SGM
raw_sgm = np.exp(mean_log) - shift

# Output the result
print(f"Raw SGM for COPT (excluding timeouts): {raw_sgm:.2f}")  # 38.67
```

**Output:**

```
Raw SGM for COPT (excluding timeouts): 38.67
```



**Verification for CLP:**

- The scaled SGM is derived by dividing the raw SGM for CLP by the raw SGM for COPT. This calculation results in **27.2**, which matches the value listed in the table on [Mittelmann's website](https://plato.asu.edu/ftp/lpopt.html).

```python
import numpy as np

# CLP runtimes from the table
runtimes = [
    269, 36, 1645, 15000, 184, 963, 106, 15000, 32, 15000, 40, 556, 297, 23, 18, 663, 188, 249, 233,
    12, 97, 16, 590, 10, 1024, 37, 211, 2823, 353, 127, 474, 14, 43, 257, 15000, 91, 104,
    42, 4970, 115, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 168,
    15000, 15000, 2337, 1082, 15000, 15000, 15000, 15000, 15000, 5001, 15000, 15000, 15000, 15000
]

# Shift value
shift = 10

# Step 1: Apply the shift to each runtime
shifted_runtimes = [max(1, runtime + shift) for runtime in runtimes]

# Step 2: Compute the natural logarithm of the shifted runtimes
log_shifted_runtimes = [np.log(value) for value in shifted_runtimes]

# Step 3: Compute the arithmetic mean of the logarithms
mean_log = np.mean(log_shifted_runtimes)

# Step 4: Exponentiate and subtract the shift to calculate the raw SGM
raw_sgm = np.exp(mean_log) - shift

# Output the result
print(f"Raw SGM for CLP: {raw_sgm:.2f}")
print(f"Scale: {raw_sgm / 38.67:.2f}")  # Scale to COPT's raw SGM
```

**Output:**
```
Raw SGM for CLP: 1052.85
Scale: 27.23
```

**Comment by siddharth-krishna** [comment]
Thanks, Jacek! That's great analysis and it looks like Mittlemann is indeed using the TO value and not excluding them. Okay, in that case let's do the same with our benchmarks for now.

For the other questions, I would say in your PR could you also add SGM of memory consumption to the website, and once we add sizes of benchmarks, let's include all sizes of benchmarks in the SGM calculations for now.

**Comment by jacek-oet** [comment]
> Does it also make sense to report the SGM of memory consumption
@siddharth-krishna 
Alongside runtime, memory consumption significantly impacts the practicality of using a solver, especially in memory-constrained environments. Including SGM for memory allows users to assess both time and resource efficiency.

Consistency with Runtime Analysis: Applying the same methodology (SGM) for memory and runtime provides a unified way to compare solver performance across benchmarks
